language: python
sudo: required
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python Mnist_triplet.py
  - python Create_128_vect.py
  - python make_prediction.py
